---

- name: Apt - install requested packages
  become: yes
  ansible.builtin.apt:
    state: present
    name: "{{ needed_packages }}"
    update_cache: true
  register: "apt_result"
  changed_when: apt_result.stdout is defined
  when:
    - needed_packages is defined
    - needed_packages

- name: Apt - remove non-requested packages
  become: yes
  ansible.builtin.apt:
    state: absent
    name: "{{ (unwanted_packages | difference(['monitoring-plugins-common', 'monitoring-plugins-basic'])) if monitoring_plugins_icinga_check_commands else unwanted_packages }}"
    autoremove: "{{ monitoring_plugins_icinga_autoremove }}"
  when:
    - monitoring_plugins_icinga_remove
    - unwanted_packages
