---

- name: Apt - install requested packages
  become: yes
  apt:
    state: present
    name: "{{ needed_packages }}"
    update_cache: true
  register: "apt_result"
  changed_when: apt_result.stdout is defined
  when:
    - needed_packages is defined
    - needed_packages

- name: Apt - remove non-requested packages
  become: yes
  apt:
    state: absent
    name: "{{ (unwanted_packages | difference(['monitoring-plugins-common', 'monitoring-plugins-basic'])) if icinga_monitoring_plugins_check_commands else unwanted_packages }}"
    autoremove: "{{ icinga_monitoring_plugins_autoremove }}"
  when:
    - icinga_monitoring_plugins_remove
    - unwanted_packages
