namespace: icinga
name: icinga
version: 0.3.2
readme: README.md
authors:
  - Lennart Betz <lennart.betz@netways.de>
  - Thilo Wening <thilo.wening@netways.de>
  - Thomas Widhalm <thomas.widhalm@netways.de>
  - Afeef Ghannam <afeef.ghannam@netways.de>
description: >
  This collection manages all Icinga 2 Components.
  Including the official repositories, server, satellite and agent installations.
  Furthermore it can easily create and distribute monitoring configuration.
license:
  - Apache-2.0
tags:
  - icinga2
  - monitoring
  - icingaweb2
  - agent
  - master
  - server
  - satellite
  - icingadb
  - icingadb_redis
  - director
dependencies: {}
repository: https://github.com/Icinga/ansible-collection-icinga
documentation: https://github.com/Icinga/ansible-collection-icinga/tree/main/doc
homepage: http://icinga.com
issues: https://github.com/Icinga/ansible-collection-icinga/issues
build_ignore:
  - yamllint.yaml
  - Makefile
  - .pylintrc
  - .cache
  - molecule
  - tests
  - .gitignore
  - .github
  - __pycache__
  - 'venv*'
  - changelogs
  - .idea
  - '*.tar.gz'
