galaxy_info:
  author: |
    - Thilo Wening <thilo.wening@netways.de>
  description: Role to install, configure or manage icingadb-redis instance.
  license: AGPL-3.0-only
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: ['7']
    - name: Debian
      versions: ['buster','bullseye']
    - name: Ubuntu
      versions: ['jammy']
  galaxy_tags:
    - icinga
    - monitoring
    - satellite
    - agent
    - server
    - master
    - icinga2
    - icingadb
    - icingadb-redis
    - redis
dependencies: []
