---
- name: Systemd reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Icinga Kubernetes restart
  ansible.builtin.service:
    name: "{{ icinga_kubernetes_service_name }}"
    state: restarted
