---

- name: Check for user in icingaweb_user
  ansible.builtin.shell: >
    {{ _tmp_mysqlcmd }}
    -Ns -e "select name from icingaweb_user where name='{{ _users.username }}'"
  # failed_when: false
  # changed_when: false
  # check_mode: false
  register: _icingaweb2_db_user

- name: debug
  debug:
    var:
      - _icingaweb2_db_user

- name: Delete user if he exists
  ansible.builtin.shell: >
    {{ _tmp_mysqlcmd }}
    -Ns -e "delete from icingaweb_user where name='{{ _users.username }}'"
  when: _icingaweb2_db_user.stdout_lines | length >= 1
  register: user_deleted

- name: Create User in icingaweb_user
  ansible.builtin.shell: >
    echo "INSERT INTO icingaweb_user
    (name, active, password_hash)
    VALUES ('{{ _users.username }}', 1, '"`php -r 'echo password_hash("{{ _users.password }}", PASSWORD_DEFAULT);'`"')"
    | {{ _tmp_mysqlcmd }} -Ns
  when: _icingaweb2_db_user.stdout_lines | length <= 0 or user_deleted.stdout_lines | length <= 0