# test_icingadb_retentions.py
icingadb_retention_history_days: 10
icingadb_retention_sla_days: 11
icingadb_retention_acknowledgement: 20
icingadb_retention_comment: 30
icingadb_retention_downtime: 10
icingadb_retention_state: 60
icingadb_retention_notification: 4
icingadb_retention_flapping: 2


icinga2_objects:
  icinga-default:
    - name: root
      type: ApiUser
      file: conf.d/apiusers.conf
      password: root
      permissions:
        - '*'
# icinga2_custom_config:
#   - name: icinga2_command
#     path: zones.d/main/commands/custom_commands.conf
#
#
# icinga2_objects:
#   icinga-default:
#     - name: eventcommand-test
#       type: EventCommand
#       file: zones.d/main/eventcommand.conf
#       command: [ ConfigDir + /scripts/eventcommand.sh ]
#     - name: scheduled-downtime-test
#       type: ScheduledDowntime
#       file: zones.d/main/ScheduledDowntime.conf
#       host_name: agent.localdomain
#       author: icingaadmin
#       comment: "Downtime"
#       fixed: false
#       duration: 30m
#       ranges:
#         sunday: 02:00-03:00
#     - name: dependency-test
#       type: Dependency
#       file: zones.d/main/dependencies.conf
#       apply: true
#       apply_target: Host
#       parent_host_name: agent.localdomain
#       disable_checks: true
#       disable_notifications: true
#       states:
#         - Up
#       assign:
#         - host.name == test.localdomain
#     - name: agent.localdomain
#       type: Endpoint
#       file: zones.d/main/hosts/agent.localdomain.conf
#     - name: agent.localdomain
#       type: Zone
#       file: zones.d/main/hosts/agent.localdomain.conf
#       parent: main
#       endpoints:
#         - agent.localdomain
#     - name: agent.localdomain
#       type: Host
#       file: zones.d/main/hosts/agent.localdomain.conf
#       check_command: hostalive
#       address: 127.0.0.1
#       check_interval: 3m
#     - name: generic-service
#       type: Service
#       file: zones.d/main/services/services.conf
#       template: true
#       check_interval: 300s
#       retry_interval: 30s
#       order: 1
#     - name: 'ping /'
#       type: Service
#       apply: true
#       file: zones.d/main/services/services.conf
#       imports:
#         - generic-service
#       check_command: ping4
#       assign:
#         - host.address
#       ignore:
#         - match(no*, host.name)
#     - name: group-ping
#       type: ServiceGroup
#       file: zones.d/main/servicegroups.conf
#       display_name: "Ping Services"
#       assign:
#         - match(ping*, service.check_command)
#     - name: group-linux
#       type: HostGroup
#       file: zones.d/main/hostgroups.conf
#       display_name: Linux Hosts
#       assign:
#         - match(linux, host.vars.os)
