---
# defaults file for monitoring_plugins

monitoring_plugins_icinga_epel: false
monitoring_plugins_icinga_crb: false
monitoring_plugins_icinga_remove: true
monitoring_plugins_icinga_autoremove: false
