---
# defaults file for monitoring_plugins

icinga_monitoring_plugins_epel: false
icinga_monitoring_plugins_crb: false
icinga_monitoring_plugins_remove: true
icinga_monitoring_plugins_autoremove: false
icinga_monitoring_plugins_dependency_repos:
  - "{{ 'powertools' if ansible_distribution_major_version == '8' and icinga_monitoring_plugins_crb else 'crb' if ansible_distribution_major_version == '9' and icinga_monitoring_plugins_crb }}"
