---

- name: Converge
  hosts: all
  vars:
    icinga2_confd: false
    icinga2_features:
      - name: perfdata
        host_perfdata_path: "/var/spool/icinga2/perfdata/host-perfdata"
        service_perfdata_path: "/var/spool/icinga2/perfdata/service-perfdata"
      - name: gelf
        host: localhost
        port: 12201
      - name: elasticsearch
        host: localhost
        port: 9200
        index: "icinga2"
        enable_send_perfdata: true
        flush_interval: 10
        flush_threshold: 1024
      - name: opentsdb
        host: localhost
        port: 4242
      - name: icingadb
        host: 127.0.0.1
      - name: notification
      - name: checker
      - name: influxdb2
        host: 127.0.0.1
        port: 8086
        organization: monitoring
        bucket: icinga2
        auth_token: testtoken123
      - name: mainlog
      - name: api
        ca_host: none
        endpoints:
          - name: "{{ ansible_fqdn }}"
        zones:
          - name: "main"
            endpoints:
              - "{{ ansible_fqdn }}"
    icinga2_config_directories:
      - zones.d/main/commands
      - zones.d/main/hosts
      - zones.d/main/services
  collections:
    - icinga.icinga
  tasks:
    - name: "Include Icinga Repos"
      include_role:
        name: repos
    - name: "Include Icinga 2"
      include_role:
        name: icinga2
