---
# The workaround for arbitrarily named role directory is important because the git repo has one name and the role within it another
# Found at: https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  collections:
    icinga.icinga
  tasks:
    - name: "Include Icinga Repos"
      include_role:
        name: repos
