---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: icinga-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  directory: tests/intergration/
lint: |
  set -e
  yamllint .
  ansible-lint .
