---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: icinga-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      icinga2_objects:
        icinga-master.localdomain:
          - name: agent.localdomain
            type: Endpoint
            file: zones.d/main/hosts/agent.localdomain.conf
          - name: agent.localdomain
            type: Host
            file: zones.d/main/hosts/agent.localdomain.conf
            check_command: hostalive
            address: 127.0.0.1
            check_interval: 3m
verifier:
  name: testinfra
  directory: tests/integration/
lint: |
  set -e
  yamllint .
  ansible-lint .
