---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: icinga-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    vvvv: True
  inventory:
    link:
      host_vars: host_vars/
verifier:
  name: testinfra
  directory: tests/integration/
lint: |
  set -e
  yamllint --no-warnings roles/
  ansible-lint roles/
