---
- name: Debian - Install IcingaDB Redis packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ icingadb_redis_packages }}"

- name: Debian - Ensure log directory exists
  when:
    - icingadb_redis_config.logfile != ""
  ansible.builtin.file:
    path: "{{ icingadb_redis_config.logfile | dirname }}"
    state: directory
    owner: "{{ icingadb_redis_user }}"
    group: "adm"
    mode: "2750"
