---
- name: RedHat - install icingadb packages
  ansible.builtin.yum:
    name: "{{ icingadb_redis_packages }}"
    state: present

- name: RedHat - Ensure log directory exists
  when:
    - icingadb_redis_logfile != ""
  ansible.builtin.file:
    path: "{{ icingadb_redis_logfile | dirname }}"
    state: directory
    owner: "{{ icingadb_redis_user }}"
    group: "{{ icingadb_redis_user }}"
    mode: "0750"
