galaxy_info:
  author: |
    - Lennart Betz <lennart.betz@netways.de>
    - Thilo Wening <thilo.wening@netways.de>
    - Thomas Widhalm <thomas.widhalm@netways.de>
  description: Role to configure or manage official Icinga repositories.
  license: AGPL-3.0-only
  min_ansible_version: 2.9
  platforms:
    - name: opensuse
      versions:
        - 15.5
    - name: SLES
      versions:
        - 15
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - icinga
    - monitoring
    - satellite
    - agent
    - server
    - master
    - icinga2
    - repos
dependencies: []
