---
- name: ICINGAWEB | Configure roles.ini (add roles and filters)
  become: true
  ansible.builtin.copy:
    owner: "{{ icingaweb2_webserver_user }}" 
    group: icingaweb2
    mode: 0660
    dest: /etc/icingaweb2/roles.ini
    content: |
      [Administrators]
      users = "*"
      permissions = "*"
