---
- name: ICINGAWEB | Configure
  ansible.builtin.blockinfile:
    dest: /etc/icingaweb2/authentication.ini
    marker: "; {mark} ANSIBLE MANAGED BLOCK EXTERNAL AUTH"
    owner: "{{ icingaweb2_webserver_user }}" 
    group: "{{ icingaweb2_webserver_group }}"
    mode: 0650
    create: true
    block: |
      [autologin]
      backend = external

- name: ICINGAWEB | Configure resources with LDAP backend
  ansible.builtin.blockinfile:
    dest: /etc/icingaweb2/resources.ini
    marker: ";{mark} ANSIBLE MANAGED BLOCK LDAP RESOURCES"
    owner: "{{ icingaweb2_webserver_user }}" 
    group: "{{ icingaweb2_webserver_group }}"
    mode: 0650
    create: true
    block: |
      [identity_openldap]
      type        = {{ icingaweb2_ldap_type }}
      hostname    = {{ icingaweb2_ldap_server }}
      port        = {{ icingaweb2_ldap_port }}
      root_dn     = "{{ icingaweb2_ldap_root_dn }}"
      bind_dn     = "{{ icingaweb2_ldap_bind_dn }}"
      bind_pw     = "{{ icingaweb2_ldap_bind_pw }}"

- name: ICINGAWEB | Configure groups and users with LDAP backend
  ansible.builtin.blockinfile:
    dest: "/etc/icingaweb2/{{ item }}.ini"
    marker: "; {mark} ANSIBLE MANAGED BLOCK {{ item | upper }}"
    create: true
    owner: "{{ icingaweb2_webserver_user }}" 
    group: "{{ icingaweb2_webserver_group }}"
    mode: 0650
    block: |
      [ldap_{{ item }}]
      backend = "ldap"
      resource = "identity_openldap"
      group_class = "{{ icingaweb2_ldap_group_class|default('groupOfNames') }}"
      user_class = "{{ icingaweb2_ldap_user_class|default('person') }}"
      user_name_attribute = "{{ icingaweb2_ldap_user_name_attribute|default('uid') }}"
      group_name_attribute = "{{ icingaweb2_ldap_group_name_attribute|default('cn') }}"
  loop:
    - groups
    - authentication
