---
- name: Override KUBECONFIG path if defined
  when: icinga_kubernetes_kubeconfig_path is defined
  block:
    - name: Create service override directory
      ansible.builtin.file:
        path: /etc/systemd/system/{{ icinga_kubernetes_service_name }}.service.d
        state: directory
        mode: '0755'
      notify:
        - Systemd reload
        - Kubernetes-restart

    - name: Create service override configuration file
      ansible.builtin.template:
        src: icinga-kubernetes-override.conf.j2
        dest: "/etc/systemd/system/{{ icinga_kubernetes_service_name }}.service.d/override.conf"
        mode: '0640'
      notify:
        - Systemd reload
        - Kubernetes-restart

- name: Ensure Kubernetes Service is running
  ansible.builtin.service:
    state: started
    enabled: yes
    name: "{{ icinga_kubernetes_service_name }}"
