---
- name: Check supported operatingsystems
  block:
    - name: Install on {{ ansible_os_family }}
      ansible.builtin.include_tasks: "install_on_{{ ansible_os_family }}.yml"
  rescue:
    - name: "OS family not supported!"
      ansible.builtin.fail:
        msg: "The OS {{ ansible_os_family }} is not supported!"

- name: Prepare fragments path
  ansible.builtin.file:
    state: directory
    path: "{{ icinga2_fragments_path }}"
    owner: root
    group: root
    mode: 0700
