---
- name: install | Check supported operatingsystems
  block:
    - name: install | Install on {{ ansible_os_family }}
      ansible.builtin.include_tasks: "install_on_{{ ansible_os_family }}.yml"
  rescue:
    - name: "install | OS family not supported!"
      ansible.builtin.fail:
        msg: "The OS {{ ansible_os_family }} is not supported!"

- name: install | Prepare fragments path
  ansible.builtin.file:
    state: directory
    path: "{{ icinga2_fragments_path }}"
    owner: root
    group: root
    mode: 0700
