---

- name: features | checker | CheckerComponent object
  icinga.icinga.icinga2_object:
    name: checker
    type: CheckerComponent
    ansible.builtin.file: features-available/checker.conf
    args: "{{ icinga2_dict_features.checker }}"
  register: result

- name: features | checker | Enhance local objects
  ansible.builtin.set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects | default([]) + [result.dest] }}"
