---

- name: features | debuglog | FileLogger object
  icinga.icinga.icinga2_object:
    name: debug-file
    type: FileLogger
    ansible.builtin.file: features-available/debuglog.conf
    path: LogDir + /debug.log
    severity: debug
    args: "{{ icinga2_dict_features.debuglog }}"
  register: result

- name: features | debuglog | Enhance local object
  ansible.builtin.set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects | default([]) + [result.dest] }}"
