---

- name: feature elasticsearch ElasticsearchWriter object
  icinga2_object:
    name: elasticsearch
    type: ElasticsearchWriter
    file: features-available/elasticsearch.conf
    args: "{{ icinga2_dict_features.elasticsearch }}"
  register: result

- set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects|default([]) + [result.dest] }}"
