---

- name: features | elasticsearch | ElasticsearchWriter object
  icinga.icinga.icinga2_object:
    name: elasticsearch
    type: ElasticsearchWriter
    ansible.builtin.file: features-available/elasticsearch.conf
    args: "{{ icinga2_dict_features.elasticsearch }}"
  register: result

- name: features | elasticsearch | Enhance local object
  ansible.builtin.set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects | default([]) + [result.dest] }}"
