---

- name: features | gelf | GelfWriter object
  icinga.icinga.icinga2_object:
    name: gelf
    type: GelfWriter
    ansible.builtin.file: features-available/gelf.conf
    args: "{{ icinga2_dict_features.gelf }}"
  register: result

- name: features | gelf | Enhance local object
  ansible.builtin.set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects | default([]) + [result.dest] }}"
