---

- name: feature influxdb GelfWriter object
  icinga2_object:
    name: gelf
    type: GelfWriter
    file: features-available/gelf.conf
    args: "{{ icinga2_dict_features.gelf }}"
  register: result

- set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects|default([]) + [result.dest] }}"
