---

- name: features | graphite | GraphiteWriter object
  icinga.icinga.icinga2_object:
    name: graphite
    type: GraphiteWriter
    file: features-available/graphite.conf
    args: "{{ __icinga2_dict_features.graphite }}"
  register: result

- name: features | graphite | Enhance local object
  ansible.builtin.set_fact:
    __icinga2_local_objects: "{{ __icinga2_local_objects | default([]) + [result.dest] }}"
