---

- name: features | livestatus | LivestatusListener object
  icinga.icinga.icinga2_object:
    name: livestatus
    type: LivestatusListener
    ansible.builtin.file: features-available/livestatus.conf
    args: "{{ icinga2_dict_features.livestatus }}"
  register: result

- name: features | livestatus | Enhance local object
  ansible.builtin.set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects | default([]) + [result.dest] }}"
