---

- name: features | mainlog | FileLogger object
  icinga.icinga.icinga2_object:
    name: main-log
    type: FileLogger
    file: features-available/mainlog.conf
    args: "{{ __icinga2_dict_features.mainlog }}"
  register: result

- name: features | mainlog | Enhance local object
  ansible.builtin.set_fact:
    __icinga2_local_objects: "{{ __icinga2_local_objects | default([]) + [result.dest] }}"
