---

- name: features | mainlog | FileLogger object
  icinga.icinga.icinga2_object:
    name: main-log
    type: FileLogger
    ansible.builtin.file: features-available/mainlog.conf
    args: "{{ icinga2_dict_features.mainlog }}"
  register: result

- name: features | mainlog | Enhance local object
  ansible.builtin.set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects | default([]) + [result.dest] }}"
