---

- name: features | notification | NotificationComponent object
  icinga.icinga.icinga2_object:
    name: notification
    type: NotificationComponent
    ansible.builtin.file: features-available/notification.conf
    args: "{{ icinga2_dict_features.notification }}"
  register: result

- name: features | notification | Enhance local object
  ansible.builtin.set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects | default([]) + [result.dest] }}"
