---

- name: feature influxdb OpenTsdbWriter object
  icinga2_object:
    name: opentsdb
    type: OpenTsdbWriter
    file: features-available/opentsdb.conf
    args: "{{ icinga2_dict_features.opentsdb }}"
  register: result

- set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects|default([]) + [result.dest] }}"
