---

- name: features | syslog | SyslogLogger object
  icinga.icinga.icinga2_object:
    name: syslog
    type: SyslogLogger
    file: features-available/syslog.conf
    args: "{{ __icinga2_dict_features.syslog }}"
  register: result

- name: features | syslog | Enhance local object
  ansible.builtin.set_fact:
    __icinga2_local_objects: "{{ __icinga2_local_objects | default([]) + [result.dest] }}"
