---
# Database Settings
icingadb_database_import_schema: false
icingadb_database_host: 127.0.0.1
icingadb_database_name: icingadb
icingadb_database_user: icingadb
icingadb_database_password: icingadb

# Redis Settings
icingadb_redis_host: 127.0.0.1
icingadb_redis_port: 6380

# Logging settings
icingadb_logging_level: info

# Variables for icingadb role
icingadb_config_dir: /etc/icingadb
icingadb_service_name: icingadb
icingadb_group: icingadb
icingadb_user: icingadb
icingadb_database_schema: "/usr/share/icingadb/schema/{{ icingadb_database_type }}/schema.sql"
icingadb_packages:
  - icingadb
