---

- name: Converge
  hosts: all
  collections:
    - netways.icinga
  pre_tasks:
    - ansible.builtin.include_role:
        name: repos
  post_tasks:
    - ansible.builtin.include_role:
        name: icingadb
