---

- name: PostgreSQL check for icingaweb db schema
  ansible.builtin.shell: >
    {{ _tmp_pgsqlcmd }}
    -w -c "select * from icingaweb_user"
  failed_when: false
  changed_when: false
  check_mode: false
  register: _icingaweb2_db_schema

- name: PostgreSQL import icingaweb db schema
  ansible.builtin.shell: >
    {{ _tmp_pgsqlcmd }}
    -w -f /usr/share/icingaweb2/schema/pgsql.schema.sql
  when:
    - _icingaweb2_db_schema.rc != 0
