name: Python Unittest
on:
  push:
    tags:
      - '*'
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 4
      matrix:
        python: ['3.11']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install "pylint>=2.14,<2.15"
      - name: Lint Python Code
        run: |
          python -m pylint plugins/


  unittest-py3:
    runs-on: ubuntu-latest

    strategy:
      # max-parallel: 4
      matrix:
        distro: [centos8, debian10]
        python: [ '3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

        with:
          python-version: ${{ matrix.python }}

      - name: Test with unittest
        run: |
          python -m unittest -v tests.unittestpy3.test_data
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}#
  unittest-py2:
    runs-on: ubuntu-latest

    strategy:
      # max-parallel: 4
      matrix:
        distro: [centos8, debian10]
        python: ['2.7']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Test with unittest
        run: |
          python -m unittest -v tests.unittestpy2.test_data
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
