name: Run python unit tests
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # max-parallel: 4
      matrix:
        distro: [centos7, centos8, debian10]
        python: ['2.7','3.6', '3.8', '3.9']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-test.txt

      - name: Test with unittest
        run: |
          python -m unittest test.py
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
